blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/slowestwind/url-shortener-ts4/discussions
    about: Please ask and answer questions here.
  - name: Support Email
    url: slowestwind@gmail.com
    about: Please ask query here.
